name: ci #nome q eu quiser
on: [push] #vai rodar em todos os push
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #pega os dados que acabou de subir e vai baixar na maquina ubuntu (actions usuario)(check.. repo)
      - uses: actions/setup-go@v2
        with:
          go-version: latest
      - run: go test
      - run: go run exec.go
